spring.application.name=pict
server.port=8083
# Database Connection Settings
spring.datasource.url=jdbc:postgresql://localhost:5432/campushire
spring.datasource.username=postgres
spring.datasource.password=Kalpesh@2005
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA & Hibernate Configurations
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JWT Settings (secret key must be hex-encoded or at least 256 bits)
campushire.jwt.secret=9a6747fc6259aa374ab4e1bb57a744b207559e3557e954a938cfa9d6bf30441a12345678
campushire.jwt.expiration-ms=86400000

# Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=kalpeshshirsath11@gmail.com
spring.mail.password=qegu dvtn sbmb mehx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.properties.mail.smtp.writetimeout=5000

# H2 Database configuration for testing
spring.h2.console.enabled=true
